export const VALIDATION_MESSAGES: Record<string, string> = {
  required: 'This field is required',
  minLength: 'Should be at least 8 characters long',
  maxLength: 'Max length exceeded',
  phoneNumber: 'Not a valid phone number',
};

export const DZONGKHAG_GEWOG: {
  [key: string]: { label: string; value: string }[];
} = {
  dzongkhag: [
    { label: 'Bumthang བུམ་ཐང་', value: 'Bumthang' },
    { label: 'Chhukha ཆུ་ཁ་', value: 'Chhukha' },
    { label: 'Dagana དར་དཀར་ན་', value: 'Dagana' },
    { label: 'Gasa མགར་ས་', value: 'Gasa' },
    { label: 'Haa ཧཱ་', value: 'Haa' },
    { label: 'Lhuentse ལྷུན་རྩེ་', value: 'Lhuentse' },
    { label: 'Mongar མོང་སྒར', value: 'Mongar' },
    { label: 'Paro སྥ་རོ་', value: 'Paro' },
    { label: 'Pema Gatshel པདྨ་དགའ་ཚལ་', value: 'PemaGatshel' },
    { label: 'Punakha སྥུ་ན་ཁ་', value: 'Punakha' },
    { label: 'Samdrup Jongkhar བསམ་གྲུབ་ལྗོངས་མཁར་', value: 'SamdrupJongkhar' },
    { label: 'Samtse བསམ་རྩེ་', value: 'Samtse' },
    { label: 'Sarpang	གསར་སྤང་', value: 'Sarpang' },
    { label: 'Thimphu	ཐིམ་ཕུག་', value: 'Thimphu' },
    { label: 'Trashigang བཀྲ་ཤིས་སྒང་', value: 'Trashigang' },
    { label: 'Trashi Yangtse བཀྲ་ཤིས་གཡང་རྩེ་', value: 'TrashiYangtse' },
    { label: 'Trongsa ཀྲོང་གསར་', value: 'Trongsa' },
    { label: 'Tsirang རྩི་རང་', value: 'Tsirang' },
    { label: 'Wangdue Phodrang དབང་འདུས་ཕོ་བྲང་', value: 'WangduePhodrang' },
    { label: 'Zhemgang གཞལ་སྒང', value: 'Zhemgang' },
  ],
  Bumthang: [
    { label: 'Chhoekhor ཆོས་འཁོར་', value: 'Chhoekhor' },
    { label: 'Chhume ཆུ་མིག་', value: 'Chhume' },
    { label: 'Ura ཨུ་ར་', value: 'Ura' },
  ],

  Chhukha: [
    { label: 'Bjachho བྱག་ཕྱོགས་', value: 'Bjachho' },
    { label: 'Bongo སྦོང་སྒོར་', value: 'Bongo' },
    { label: 'Chapcha སྐྱབས་ཆ་', value: 'Chapcha' },
    { label: 'Darla དར་ལ་', value: 'Darla' },
    { label: 'Dungna གདུང་ན་', value: 'Dungna' },
    { label: 'Geling དགེ་གླིང་', value: 'Geling' },
    { label: 'Getana གད་སྟག་ན་', value: 'Getana' },
    { label: 'Lokchina ལོག་ཅི་ན་', value: 'Lokchina' },
    { label: 'Metakha སྨད་བཏབ་ཁ་', value: 'Metakha' },
    {
      label: 'Phuentsholing ཕུན་ཚོགས་གླིང་',
      value: 'Phuentsholing',
    },
    { label: 'Sampheling བསམ་འཕེལ་གླིང་', value: 'Sampheling' },
  ],
  Dagana: [
    { label: 'Dorona རྡོ་རོ་ན་', value: 'Dorona' },
    { label: 'Drujegang འབྲུག་རྗེས་སྒང་', value: 'Drujegang' },
    { label: 'Gesarling གེ་སར་གླིང་', value: 'Gesarling' },
    { label: 'Goshi སྒོ་བཞི་', value: 'Goshi' },
    { label: 'Kana བཀར་ན་', value: 'Kana' },
    { label: 'Karmaling ཀརྨ་གླིང་', value: 'Karmaling' },
    { label: 'Khebisa ཁེ་སྦིས་ས་', value: 'Khebisa' },
    { label: 'Lajab ལ་རྒྱབ་', value: 'Lajab' },
    {
      label: 'Lhamoi Zingkha ལྷ་མོའི་རྫིང་ཁ་',
      value: 'Lhamoi Zingkha',
    },
    { label: 'Nichula ནི་ཅུ་ལ་', value: 'Nichula' },
    { label: 'Trashiding བཀྲིས་ལྡིང་', value: 'Trashiding' },
    { label: 'Tsangkha གཙང་ཁ་', value: 'Tsangkha' },
    { label: 'Tsendagang བཙན་མདའ་སྒང་', value: 'Tsendagang' },
    { label: 'Tseza བརྩེ་ཟ་', value: 'Tseza' },
  ],
  Gasa: [
    { label: 'Khamaed ཁ་སྨད་', value: 'Khamaed' },
    { label: 'Khatoe ཁ་སྟོད་', value: 'Khatoe' },
    { label: 'Laya ལ་ཡ་', value: 'Laya' },
    { label: 'Lunana ལུང་ནག་ན་', value: 'Lunana' },
  ],
  Haa: [
    { label: 'Bji སྦྱིས་', value: 'Bji' },
    { label: 'Gakiling དགའ་སྐྱིད་གླིང་', value: 'Gakiling' },
    { label: 'Katsho སྐར་ཚོགས་', value: 'Katsho' },
    { label: 'Samar ས་དམར་', value: 'Samar' },
    { label: 'Sangbay གསང་སྦས་', value: 'Sangbay' },
    { label: 'Uesu དབུས་སུ་', value: 'Uesu' },
  ],
  Lhuentse: [
    { label: 'Gangzur སྒང་ཟུར་', value: 'Gangzur' },
    { label: 'Khoma མཁོ་མ་', value: 'Khoma' },
    { label: 'Jarey རྒྱ་རས་', value: 'Jarey' },
    { label: 'Kurtoed ཀུར་སྟོད་', value: 'Kurtoed' },
    { label: 'Menbi སྨན་སྦིས་', value: 'Menbi' },
    { label: 'Metsho སྨད་མཚོ་', value: 'Metsho' },
    { label: 'Minjay སྨིན་རྒྱས་', value: 'Minjay' },
    { label: 'Tsenkhar སཙན་མཁར་', value: 'Tsenkhar' },
  ],

  Mongar: [
    { label: 'Balam བ་ལམ་', value: 'Balam' },
    { label: 'Chali ཅ་གླིང་', value: 'Chali' },
    { label: 'Chaskhar ལྕགས་ས་མཁར་', value: 'Chaskhar' },
    { label: 'Drametse དགྲ་མེད་རྩེ་', value: 'Drametse' },
    { label: 'Drepong འབྲེས་སྤུངས་', value: 'Drepong' },
    { label: 'Gongdue དགོངས་འདུས་', value: 'Gongdue' },
    { label: 'Jurmey འགྱུར་མེད་', value: 'Jurmey' },
    { label: 'Kengkhar སྐྱེངས་མཁར་', value: 'Kengkhar' },
    { label: 'Mongar མོང་སྒར་', value: 'Mongar' },
    { label: 'Narang ན་རང་', value: 'Narang' },
    { label: 'Ngatshang སྔ་ཚང་', value: 'Ngatshang' },
    { label: 'Saling ས་གླིང་', value: 'Saling' },
    { label: 'Shermuhoong ཤེར་མུ་ཧཱུྃ་', value: 'Shermuhoong' },
    { label: 'Silambi སི་ལམ་སྦི་', value: 'Silambi' },
    { label: 'Thangrong ཐང་རོང་', value: 'Thangrong' },
    { label: 'Tsakaling ཙ་ཀ་གླིང་', value: 'Tsakaling' },
    { label: 'Tsamang རྩ་མང་', value: 'Tsamang' },
  ],
  Paro: [
    { label: 'Dokar རྡོ་དཀར་', value: 'Dokar' },
    { label: 'Dopshari རྡོབ་ཤར་རི་', value: 'Dopshari' },
    { label: 'Doteng རྡོ་སྟེང་', value: 'Doteng' },
    { label: 'Hungrel ཧཱུྃ་རལ་', value: 'Hungrel' },
    { label: 'Lamgong ལམ་གོང་', value: 'Lamgong' },
    { label: 'Lungnyi ལུང་གཉིས་', value: 'Lungnyi' },
    { label: 'Naja ན་རྒྱ་', value: 'Naja' },
    { label: 'Shapa ཤར་པ་', value: 'Shapa' },
    { label: 'Tsento བཙན་ཏོ་', value: 'Tsento' },
    { label: 'Wangchang ཝང་ལྕང་', value: 'Wangchang' },
  ],
  PemaGatshel: [
    { label: 'Chimoong ཕྱི་མུང་', value: 'Chimoong' },
    { label: 'Chokhorling ཆོས་འཁོར་གླིང་', value: 'Chokhorling' },
    { label: 'Chongshing ལྕོང་ཤིང་', value: 'Chongshing' },
    { label: 'Dechheling བདེ་ཆེན་གླིང་', value: 'Dechheling' },
    { label: 'Dungmaed གདུང་སྨད་', value: 'Dungmaed' },
    { label: 'Khar མཁར་', value: 'Khar' },
    { label: 'Nanong ན་ནོང་', value: 'Nanong' },
    { label: 'Norbugang ནོར་བུ་སྒང་', value: 'Norbugang' },
    { label: 'Shumar ཤུ་མར་', value: 'Shumar' },
    { label: 'Yurung ཡུ་རུང་', value: 'Yurung' },
    { label: 'Zobel བཟོ་སྦལ་', value: 'Zobel' },
  ],
  Punakha: [
    { label: 'Barp བརཔ་', value: 'Barp' },
    { label: 'Chhubug ཆུ་སྦུག་', value: 'Chhubug' },
    { label: 'Dzomi འཅོམས་མི་', value: 'Dzomi' },
    { label: 'Goenshari དགོམ་ཤ་རི་', value: 'Goenshari' },
    { label: 'Guma གུ་མ་', value: 'Guma' },
    { label: 'Kabisa དཀར་སྦི་ས་', value: 'Kabisa' },
    { label: 'Lingmukha གླིང་མུ་ཁ་', value: 'Lingmukha' },
    {
      label: 'Shenga Bjemi ཤེལ་རྔ་_སྦྱེ་མི་',
      value: 'Shenga Bjemi',
    },
    { label: 'Talog རྟ་ལོག་', value: 'Talog' },
    { label: 'Toepisa སཏོད་པའི་ས་', value: 'Toepisa' },
    { label: 'Toewang སྟོད་ཝང་', value: 'Toewang' },
  ],

  SamdrupJongkhar: [
    { label: 'Dewathang དབེ་བ་ཐང་', value: 'Dewathang' },
    { label: 'Gomdar སྒམ་དར་', value: 'Gomdar' },
    { label: 'Langchenphu གླང་ཅན་ཕུ་', value: 'Langchenphu' },
    { label: 'Lauri ལའུ་རི་', value: 'Lauri' },
    { label: 'Martshala མར་ཚྭ་ལ་', value: 'Martshala' },
    { label: 'Orong ཨོ་རོང་', value: 'Orong' },
    { label: 'Pemathang པདྨ་ཐང་', value: 'Pemathang' },
    { label: 'Phuntshothang ཕུན་ཚོགས་ཐང་', value: 'Phuntshothang' },
    { label: 'Samrang བསམ་རང་', value: 'Samrang' },
    { label: 'Serthi གསེར་ཐིག་', value: 'Serthi' },
    { label: 'Wangphu ཝང་ཕུག་', value: 'Wangphu' },
  ],

  Samtse: [
    { label: 'Dungtoe གདུང་སྟོད་', value: 'Dungtoe' },
    { label: 'Dophoogchen རྡོ་ཕུག་ཅན་', value: 'Dophoogchen' },
    { label: 'Duenchukha བདུམ་ཅུ་ཁ་', value: 'Duenchukha' },
    {
      label: 'Namgaychhoeling རྣམ་རྒྱས་ཆོས་གླིང་',
      value: 'Namgaychhoeling',
    },
    { label: 'Norbugang ནོར་བུ་སྒང་', value: 'Norbugang' },
    { label: 'Norgaygang ནོར་རྒྱས་སྒང་', value: 'Norgaygang' },
    { label: 'Pemaling པདྨ་གླིང་', value: 'Pemaling' },
    {
      label: 'Phuentshogpelri ཕུན་ཚོགས་དབལ་རི་',
      value: 'Phuentshogpelri',
    },
    { label: 'Samtse བསམ་རྩེ་', value: 'Samtse' },
    {
      label: 'Sangngagchhoeling གསང་སྔགས་ཆོས་གླིང་',
      value: 'Sangngagchhoeling',
    },
    { label: 'Tading རྟ་སྡིང་', value: 'Tading' },
    {
      label: 'Tashicholing བཀྲིས་ཙོས་གླིང་',
      value: 'Tashicholing',
    },
    { label: 'Tendruk བསྟང་འབྲུག', value: 'Tendruk' },
    { label: 'Ugentse ཨྱོན་རྩེ་', value: 'Ugentse' },
    { label: 'Yoeseltse འོད་གསལ་རྩེ་', value: 'Yoeseltse' },
  ],

  Sarpang: [
    { label: 'Chhuzagang ཆུ་འཛག་སྒང་', value: 'Chhuzagang' },
    { label: 'Chhudzom ཆུ་འཛོམས་', value: 'Chhudzom' },
    { label: 'Dekiling བདེ་སྐྱིད་གླིང་', value: 'Dekiling' },
    { label: 'Gakiling དགའ་སྐྱིད་གླིང་', value: 'Gakiling' },
    { label: 'Gelephu དགེ་ལེགས་ཕུ་', value: 'Gelephu' },
    { label: 'Jigmechholing འཇིགས་མེད་ཆོས་གླིང་', value: 'Jigmechholing' },
    { label: 'Samtenling བསམ་གཏན་གླིང་', value: 'Samtenling' },
    { label: 'Senggey སེ་ངྒེ་', value: 'Senggey' },
    { label: 'Sherzhong གསེར་གཞོང་', value: 'Sherzhong' },
    { label: 'Shompangkha ཤོམ་སྤང་ཁ་', value: 'Shompangkha' },
    { label: 'Tareythang རྟ་རས་ཐང་', value: 'Tareythang' },
    { label: 'Umling ཨུམ་གླིང་', value: 'Umling' },
  ],
  Thimphu: [
    { label: 'Chang ལྕང་', value: 'Chang' },
    { label: 'Darkala དར་དཀར་ལ་', value: 'Darkala' },
    { label: 'Genye དགེ་བསྙེན་', value: 'Genye' },
    { label: 'Kawang ཀ་ཝང་', value: 'Kawang' },
    { label: 'Lingzhi གླིང་གཞི་', value: 'Lingzhi' },
    { label: 'Mewang སྨད་ཝང་', value: 'Mewang' },
    { label: 'Naro ན་རོ་', value: 'Naro' },
    { label: 'Soe སྲོས་', value: 'Soe' },
  ],

  Trashigang: [
    { label: 'Bartsham བར་མཚམས་', value: 'Bartsham' },
    { label: 'Bidung སྦིས་གདུང་', value: 'Bidung' },
    { label: 'Kanglung བཀང་ལུང་', value: 'Kanglung' },
    { label: 'Kangpar རྐང་པར་', value: 'Kangpar' },
    { label: 'Khaling ཁ་གླིང་', value: 'Khaling' },
    { label: 'Lumang ཀླུ་མང་', value: 'Lumang' },
    { label: 'Merag མེ་རག་', value: 'Merag' },
    { label: 'Phongmed ཕོངས་མེད་', value: 'Phongmed' },
    { label: 'Radi ར་དི་', value: 'Radi' },
    { label: 'Sagteng སག་སྟེང་', value: 'Sagteng' },
    { label: 'Samkhar བསམ་མཁར་', value: 'Samkhar' },
    { label: 'Shongphoog ཤོང་ཕུག་', value: 'Shongphoog' },
    { label: 'Thrimshing ཁྲིམས་ཤིང་', value: 'Thrimshing' },
    { label: 'Uzorong ཨུ་མཛོ་རོང་', value: 'Uzorong' },
    { label: 'Yangnyer ཡངས་ཉེར་', value: 'Yangnyer' },
  ],
  TrashiYangtse: [
    { label: 'Bumdeling བུམ་སྡེ་གླིང་', value: 'Bumdeling' },
    { label: 'Jamkhar འཇམ་མཁར་', value: 'Jamkhar' },
    { label: 'Khamdang ཁམས་དྭངས་', value: 'Khamdang' },
    { label: 'Ramjar རམ་སྦྱར་', value: 'Ramjar' },
    { label: 'Toetsho སྟོད་མཚོ་', value: 'Toetsho' },
    { label: 'Tomzhang སྟོང་མི་གཞང་ས་', value: 'Tomzhang' },
    { label: 'Yalang ཡ་ལང་', value: 'Yalang' },
    { label: 'Yangtse གཡང་རྩེ་', value: 'Yangtse' },
  ],
  Trongsa: [
    { label: 'Dragteng བྲག་སྟེང་', value: 'Dragteng' },
    { label: 'Korphoog སྐོར་ཕུག་', value: 'Korphoog' },
    { label: 'Langthil གླང་མཐིལ་', value: 'Langthil' },
    { label: 'Nubi ནུ་སྦིས་', value: 'Nubi' },
    { label: 'Tangsibji སྟང་སི་སྦྱིས་', value: 'Tangsibji' },
  ],
  Tsirang: [
    { label: 'Barshong བར་གཤོང་', value: 'Barshong' },
    { label: 'Dunglegang དུང་ལ་སྒང་', value: 'Dunglegang' },
    { label: 'Gosarling སྒོ་གསར་གླིང་', value: 'Gosarling' },
    { label: 'Kikhorthang དཀྱིལ་འཁོར་ཐང་', value: 'Kikhorthang' },
    { label: 'Mendrelgang མནྜལ་སྒང་', value: 'Mendrelgang' },
    { label: 'Patshaling པ་ཚ་གླིང་', value: 'Patshaling' },
    { label: 'Phuntenchu སྤུང་རྟེན་ཆུ་', value: 'Phuntenchu' },
    { label: 'Rangthangling རང་ཐང་གླིང་', value: 'Rangthangling' },
    { label: 'Semjong སེམས་ལྗོངས་', value: 'Semjong' },
    { label: 'Sergithang གསེར་གྱི་ཐང་', value: 'Sergithang' },
    { label: 'Tsholingkhar མཚོ་གླིང་མཁར་', value: 'Tsholingkhar' },
    { label: 'Tsirangtoe རྩི་རང་སྟོད་', value: 'Tsirangtoe' },
  ],
  WangduePhodrang: [
    { label: 'Athang ཨ་ཐང་', value: 'Athang' },
    { label: 'Bjendag སྦྱེད་ནག་', value: 'Bjendag' },
    { label: 'Darkar དར་དཀར་', value: 'Darkar' },
    { label: 'Dangchu དྭངས་ཆུ་', value: 'Dangchu' },
    { label: 'Gangteng སྒང་སྟེང་', value: 'Gangteng' },
    {
      label: 'Gasetsho Gom དགའ་སེང་ཚོ་གོངམ་',
      value: 'Gasetsho Gom',
    },
    {
      label: 'Gasetsho Wom དགའ་སེང་ཆོ་འོགམ་',
      value: 'Gasetsho Wom',
    },
    { label: 'Kazhi ཀ་གཞི་', value: 'Kazhi' },
    { label: 'Nahi ན་ཧི་', value: 'Nahi' },
    { label: 'Nyisho ཉི་ཤོག་', value: 'Nyisho' },
    { label: 'Phangyul ཕངས་ཡུལ་', value: 'ura' },
    { label: 'Phobji ཕོབ་སྦྱིས་', value: 'Phobji' },
    { label: 'Ruepisa རུས་སྦིས་ས་', value: 'Ruepisa' },
    { label: 'Sephu སྲས་ཕུག་', value: 'Sephu' },
    { label: 'Thedtsho ཐེད་ཚོ་', value: 'Thedtsho' },
  ],
  Zhemgang: [
    { label: 'Bardo བར་རྡོ་', value: 'Bardo' },
    { label: 'Bjoka འབྱོག་ཀ་', value: 'Bjoka' },
    { label: 'Goshing སྒོ་ཤིང་', value: 'Goshing' },
    { label: 'Nangkor ནང་སྐོར་', value: 'Nangkor' },
    { label: 'Ngangla ངང་ལ་', value: 'Ngangla' },
    { label: 'Phangkhar ཕང་མཁར་', value: 'Phangkhar' },
    { label: 'Shingkhar ཤིང་མཁར་', value: 'Shingkhar' },
    { label: 'Trong ཀྲོང་', value: 'Trong' },
  ],
};
export const NAVIGATION_HEADER_CONFIG = {
  headerStyle: {
    backgroundColor: '#49C1A4',
  },
  headerTitleStyle: {
    color: '#FAFAFA',
  },
  headerTintColor: '#FAFAFA',
};

export const PHONE_NUMBER_EXPRESSION =
  /^((\\+[1-9]{1,4}[ \\-]*)|(\\([0-9]{2,3}\\)[ \\-]*)|([0-9]{2,4})[ \\-]*)*?[0-9]{3,4}?[ \\-]*[0-9]{3,4}?$/;

export const BHT_PHONE_NUMBER_EXPRESSION = /^([17][7])[0-9]{6}$/;

export const ERROR_MESSAGES = {
	genericError: 'Oops something went wrong'
}
